name 'learn_chef_cb_2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures learn_chef_cb_2'
long_description 'Installs/Configures learn_chef_cb_2'
version '0.1.0'
