name 'learn_chef_learn_cb_1'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures learn_chef_learn_cb_1'
long_description 'Installs/Configures learn_chef_learn_cb_1'
version '0.1.0'
