name 'myfirstcookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures myfirstcookbook'
long_description 'Installs/Configures myfirstcookbook'
version '0.1.0'
