name 'learn_chef_file'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures learn_chef_file'
long_description 'Installs/Configures learn_chef_file'
version '0.1.0'
