name 'cookbook1'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbook1'
long_description 'Installs/Configures cookbook1'
version '0.1.0'
